# Generated by Django 3.2.6 on 2021-08-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='districts/')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('metro', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
    ]
