# Generated by Django 3.2.6 on 2021-08-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210813_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='slug',
            new_name='url',
        ),
    ]
