# Generated by Django 3.2.6 on 2021-08-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_slug_districts_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='districts_image/', verbose_name='Изображение')),
                ('districts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.districts', verbose_name='Район')),
            ],
        ),
    ]
