# Generated by Django 3.2.6 on 2021-08-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_districtsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtsimage',
            options={'verbose_name': 'Фотографии района', 'verbose_name_plural': 'Фотографии района'},
        ),
        migrations.AddField(
            model_name='districts',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
