# Generated by Django 3.2.6 on 2021-08-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210815_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='places_nearbly',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
