# Generated by Django 3.2.6 on 2021-08-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210815_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apart_name', models.CharField(max_length=50, null=True)),
                ('apart_image', models.ImageField(null=True, upload_to='districts_apart/')),
                ('apart_price', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
            },
        ),
        migrations.RemoveField(
            model_name='districts',
            name='apart_image',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='apart_price',
        ),
    ]
