# Generated by Django 3.2.6 on 2021-08-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210815_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.districts'),
        ),
    ]
