# Generated by Django 3.2.6 on 2021-08-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='DistrictsNews',
        ),
    ]
