# Generated by Django 3.2.6 on 2021-08-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_news_districtsnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtsnews',
            name='districts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.districts', verbose_name='Район'),
        ),
    ]
