# Generated by Django 3.2.6 on 2021-08-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_districtsnews_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtsnews',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='districtsnews',
            name='image',
            field=models.ImageField(null=True, upload_to='districts_news/'),
        ),
    ]
