# Generated by Django 3.2.6 on 2021-08-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210816_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtsnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='districts_news/'),
        ),
    ]
