# Generated by Django 3.2.6 on 2021-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_districts_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtsimage',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
