# Generated by Django 3.2.6 on 2021-08-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_reviews_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
    ]
