# Generated by Django 3.2.6 on 2021-09-01 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_reviews_districts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата'),
        ),
    ]
