# Generated by Django 3.2.6 on 2021-09-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='districts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.districts', verbose_name='район'),
        ),
    ]
